name: 'Dokku Deploy - Github Action'
description: 'Deploy applications to Dokku'
author: 'Vitaly Liber'
branding:
  icon: 'upload-cloud'  
  color: 'blue'
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: 'docker'
  image: 'Dockerfile'
